version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - nodejs

  node:
    image: node
    volumes:
      - .:/app
    ports:
      - 3000:3000
    working_dir: /app
    depends_on:
      - mongo
    networks:
      - nodejs
  
networks:
  nodejs:
    driver: bridge